### ISSUE TITLE
Roadmap tab: wrong answer sets referenced in the data validation for the Implementation business function.

### ISSUE THREAD

**Issue by nessimk** [owaspsamm/toolbox-spreadsheet#1]
I noticed some activities in the Roadmap reference the wrong Answer sets. As a result, the same assessment question (e.g. Is the build process fully automated?) have the correct answers for the first maturity levels & phases (e.g. Yes, for most or all of the applications) but the wrong ones for later ones (e.g. Yes, for at least half of the obligations). Among other things this completely breaks the roadmap chart & scores.

I think the following is the full list of broken activities (it was late and I was fixing them as I was working so my record keeping may not have been the most thorough):

-  Implementation
   -  Secure Build
      -  Build Process: Phases 3, 4
      -  Software Dependencies: Phases 3, 4

   -   Secure Deployment
       -  Deployment Process: Phase 3
       -  Secret Management: Phase 3

   - Defect Management
       - both streams?: Phases 3, 4

Most (if not all) of these mistakenly use AnsD as the source of data validation instead of AnsF.
Fix by changing the value for those cells in Data Validation -> Settings -> Source 

I can submit a PR with a fixed sheet next week. In the meantime, a happy new year to all!

cheers,
nessim

**Comment by RossBarnie** [comment]
I have a similar problem with the entire governance section which is using the wrong table for every answer, there are more errors but at a certain point I stopped counting, example screenshot attached with hidden columns unhidden.
![image](https://user-images.githubusercontent.com/2567153/157690152-db2fec15-5fd4-45e4-b91d-27389e4c125f.png).

G18 cell has formula `=IFERROR(VLOOKUP(F18,AnsYTBL,2,FALSE),0)`, I believe this should be `=IFERROR(VLOOKUP(F18,AnsNTBL,2,FALSE),0)`.

Briefly looking into the code I'm not sure where this is introduced. The core questions and answer set reference seem correct so I assume it's here where that's being translated to the spreadsheet.

**Comment by BjLill** [comment]
Had two problems with the official v2.03: 1) Same issue as mentioned above: would not update Roadmap tab properly 2) Vital functions (answer selector) did not work on google sheets. Tested now with version (of today?) found in toolbox folder of the samm-2.0 repo. This version fixed both issues! Great job!

**Comment by shraddhag** [comment]
@BjLill: can you provide url from where you could download the working excel sheet please? Thanks.

**Comment by dkefer** [comment]
@nessimk The 2.0.4 release should fix all issues with the roadmap tab according to my testing. If you find a minute, could you double check and confirm?

**Comment by BjLill** [comment]
Did a quick test on the 2.0.4 version and it does solve the issues found
when running from Excel or LibreOffice. I still have problems making it
work from Google sheets. From the Answer column in the Interview tab it
still just displays "Loading..." rather that coming up with the expected
options [image: image.png]
What is strange is that this works perfectly in the version I previously
mentioned which can be found within the Samm-2.0 zip found here: Release
OWASP SAMM version 2 · OWASP/samm · GitHub
<https://github.com/OWASP/samm/releases/tag/v2.0>
File name is: SAMM_Assessment_Toolbox_v2.0-WIP
