### ISSUE TITLE
"Phase" is written with both Roman and Arabic numerals

### ISSUE THREAD

**Issue by AnthonyMastrean** [owaspsamm/toolbox-spreadsheet#15]
Roman and Arabic numerals are mixed throughout the sheet (for example, "Phase IV" vs. "Phase 4"). It would look nicer to have a consistent style. I'd recommend sticking to the Arabic numerals, since some projects will need more than the four preloaded phases and writing out Arabic numerals should be more universal than using Roman numerals.

**Comment by maximbaele** [comment]
fixed by https://github.com/owaspsamm/toolbox-spreadsheet/pull/24
