### ISSUE TITLE
calculation of the Rating does not work in other Excel language/regional settings

### ISSUE THREAD

**Issue by SebaDele** [owaspsamm/toolbox-spreadsheet#16]
In some situations the calculation of the Rating does not work
![image001](https://user-images.githubusercontent.com/5277413/200414801-909a0025-8e2a-4059-8164-de45f86cfcae.jpg)
The attachment is from a v2.0.7 on a German version of Excel.
Asked to get the  settings / configuration (language / regional settings) and Excel version.

We have seen similar issues on Finnish and Brazilian systems, but have not been able to pinpoint the exact root problem yet.

**Comment by SebaDele** [comment]
Regarding the missing formulas in column H.
These are only necessary in the first stream, as they average both streams into 3 values that are then summed up towards the maturity level in column J.
The value calculated in your screenshot is actually correct: 0.88 maturity.
So it seems that the formulas are working correctly.

**Comment by bschuette** [comment]
I still have this issues with German Excel versions and latest release 2.0.8. Switched Excel to English and it works. Tested on Excel 16.16 on MacOS and latest Office 16 Excel on Windows. German LibreOffice works fine.

**Comment by kmoens** [comment]
I'm seeing similar issues for the Dutch version.
