### ISSUE TITLE
Typo in roadmap chart

### ISSUE THREAD

**Issue by mtausig** [owaspsamm/toolbox-spreadsheet#17]
In the diagram on the *roadmap chart* tab, the description say `Strategy & metrics` instead of `Strategy & Metrics`.
![image](https://user-images.githubusercontent.com/1511226/212326559-91ad0b20-1188-4f12-8ae0-ad2d9f7bf5be.png)

**Comment by maximbaele** [comment]
Fixed by https://github.com/owaspsamm/toolbox-spreadsheet/pull/24
I have to mention though that we decided to hide this sheet by default, as it was mainly duplicating information
