### ISSUE TITLE
Rounding error in gap table

### ISSUE THREAD

**Issue by mtausig** [owaspsamm/toolbox-spreadsheet#18]
There is a rounding error in the *Current gap* column on the `Roadmap Chart` tab of the toolbox:

![image](https://user-images.githubusercontent.com/1511226/214593285-2277b0d6-ab45-4a1a-9573-48dda5c22dda.png)

Under *Eductation & Guidance* in the screenshot, the gap is displayed as `0,88` but it should actually be `1,50-0,63=0,87`

I assume, that both 0,63 and 0,88 are rounded values leading to this error. I find that confusing. The gap should just be the difference of the values shown in the table and not that of their unrounded base values.

**Comment by maximbaele** [comment]
The sheet has since been removed from the toolbox

**Comment by mtausig** [comment]
Why has it been removed @maximbaele ? I found the graphs in there quite helpful.
