### ISSUE TITLE
Align colors in spreadsheets to colors in model diagram

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/toolbox-spreadsheet#19]

**Comment by Pat-Duarte** [comment]
Based on https://github.com/owaspsamm/website/issues/89, created by @mtausig

**Comment by maximbaele** [comment]
@Pat-Duarte , can you get me the color scheme please, in hex colors?

**Comment by Pat-Duarte** [comment]
![Image](https://github.com/owaspsamm/toolbox-spreadsheet/assets/41348252/df40123c-47ba-4e75-84d8-a24a5ed147d0)

**Comment by Pat-Duarte** [comment]
The font is Open Sans
The font for main headings is Days One

**Comment by maximbaele** [comment]
Fixed by https://github.com/owaspsamm/toolbox-spreadsheet/pull/24
