### ISSUE TITLE
The Google Sheets version 2.0.3 is not working properly

### ISSUE THREAD

**Issue by fnavalca** [owaspsamm/toolbox-spreadsheet#2]
Hello,

I was trying to use the Google Sheets version of your assessment but I am not able to answer the questions because Google Sheets does not allow set use any formula for drop down lists of Data Validation. [Source](https://support.google.com/docs/thread/18864947/indirect-formula-in-data-validation-to-populate-dynamic-drop-down?hl=en)

In Microsoft Excel is working properly and also in older versions (I think is the 2.0).

If you can fix it, it would be amazing.

Thank you!

**Comment by dkefer** [comment]
If you need to use the spreadsheet version on Google, I'd recommend to use the "Google Spreadsheet Toolbox" linked at https://owaspsamm.org/assessment/. Using the INDIRECT formula is currently not trivially replaceable in the current build process.

**Comment by ralfnetto** [comment]
Hello, 

I have the same issue. Will it be fixed soon?

Thanks!

**Comment by infosecdad** [comment]
Should be fixed with the upcoming release of v2.0.6, will notify here when released.
