### ISSUE TITLE
The Excel spreadsheet doesn't work in french Excel

### ISSUE THREAD

**Issue by osechet** [owaspsamm/toolbox-spreadsheet#22]
Hi!
The Excel spreadsheet doesn't work with a french Excel (and probably with other languages) because of the relative references in `indirect()` functions, in the _G_ column.
`INDIRECT("LC[-1]";0)` returns an invalid reference error. To work in a french Excel, it has to be `INDIRECT("LC(-1)";0)`.

A possible solution is to use a combination of `address()`, `row()` and `column()` instead of `LC[x]`: `INDIRECT(ADDRESS(ROW();COLUMN()-1);1)`

**Comment by maximbaele** [comment]
Hi! Thank you for reporting this and for the pull request, we have recently updated the Excel toolbox and have a release candidate ready. I will review the proposed changes you made, but we have chosen to move away from using the "VLOOKUP" function as it will be deprecated in the future, apparently. 
The new document uses INDEX/MATCH with the intent of being as generic and widely compatible as possible.

**Comment by maximbaele** [comment]
[SAMM_spreadsheet_i10n_design_fixedfinal.xlsx](https://github.com/user-attachments/files/15859329/SAMM_spreadsheet_i10n_design_fixedfinal.xlsx)

Hi, if you want you can take this version for a spin, let me know if you run into any errors, we are now testing this version with the core team. Like you found out too, there was indeed an issue with some formulas and the indirect references not translating into several other languages. We moved to index/match and A1 notation with the aim of maximizing compatibility with excel versions, languages and spreadsheet programs.

Even if your pull request did not get merged, we really appreciate the effort and willingness to contribute!

**Comment by maximbaele** [comment]
Fixed by  https://github.com/owaspsamm/toolbox-spreadsheet/pull/24
