### ISSUE TITLE
SAMM toolbox excel v2.0.4 roadmap chart issue

### ISSUE THREAD

**Issue by shraddhag** [owaspsamm/toolbox-spreadsheet#5]
Hello @dkefer 

I download latest toolbox excel from, https://github.com/owaspsamm/core/releases/tag/v2.0.4

On the 'Roadmap Chart' tab, I was expecting the score to increase by phase (from As-Is .....To-Be), but found that the scores remains same for all the 4 maturity phases. Due to this the pie radar charts on 'Scorecard' tab look same for all 4 phases. Please see below screenshot, the score is same for all phases, hence the current gap is always 0.00

![image](https://user-images.githubusercontent.com/8229007/160437888-269ff13f-9b0b-4463-9e94-80a02cbfc72f.png)

**Comment by shraddhag** [comment]
@dkefer Can you please advice if the above mentioned issue will be fixed sometime soon?

**Comment by infosecdad** [comment]
@shraddhag Did someone update the projected answers in the 'Roadmap' tab? By default all the Phases inherit the answers from the interview.  The 'Roadmap' tab has the answers for current and the 4 phases. It's designed to have someone project updated answers for each phase showing a projected score change. The table and spider charts in the 'Roadmap Chart' tab work off the updated data in the 'Roadmap' tab.
