### ISSUE TITLE
colors not changing between phases under Implementation

### ISSUE THREAD

**Issue by SebaDele** [owaspsamm/toolbox-spreadsheet#6]
raised by @al in Slack - https://owasp.slack.com/archives/C0VF1EJGH/p1648503557375079
"Roadmap still has issues including color coding changes between phases under Implementation."
not sure if there are others besides the color coding changes (not changing to green/red) => can be solved by applying the same formatting to the Implementation rows.

**Comment by dkefer** [comment]
Fixed with Core release v2.0.5: https://github.com/owaspsamm/core/releases/tag/v2.0.5
